MACOSX_DEPLOYMENT_TARGET:  # [osx]
  - macos-11               # [osx]
c_compiler:                # [win]
  - vs2019                 # [win]
cxx_compiler:              # [win]
  - vs2019                 # [win]

