{% set version = "0.1.8" %}

package:
  name: chemicalfun
  version: {{ version }}

source:
  url: https://bitbucket.org/gems4/chemicalfun/get/v{{ version }}.tar.gz
  sha256: a51341f0a89b0a43e3e50d43bb22d7aa79c86448f4c53869369a16f29afcc965

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - pip
    - cmake
    - ninja  # [win]
    - make  # [unix]
  host:
    - pybind11
    - eigen >=3.4.0
    - python
    - spdlog >=1.10.0
    - nlohmann_json >=3.7.0
  run:
    - python

test:
  commands:
    - conda list
    - test -d ${PREFIX}/include/ChemicalFun  # [unix]
    - test -f ${PREFIX}/include/ChemicalFun/FormulaParser.h  # [unix]
    - if exist %LIBRARY_PREFIX%\include\ChemicalFun\FormulaParser.h (exit 0) else (exit 1)  # [win]
  imports:
    - chemicalfun

about:
  home: https://bitbucket.org/gems4/chemicalfun
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: Library for generating balanced chemical reactions and for parsing and calculating properties of chemical formulas.
  doc_url: https://bitbucket.org/gems4/chemicalfun
  dev_url: https://bitbucket.org/gems4/chemicalfun

extra:
  recipe-maintainers:
    - gdmiron
    - dimitrikulik
    - sdmytrievs
