{% set version = "0.1.11" %}

package:
  name: chemicalfun
  version: {{ version }}

source:
  url: https://github.com/thermohub/chemicalfun/archive/v{{ version }}.tar.gz
  sha256: 1a1c83038f03e5629f16a1787307022e190774fa56823a41c83e02912d23e897

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja  # [win]
    - make   # [unix]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
  host:
    - pybind11
    - eigen >=3.4.0
    - python
    - pip
    - spdlog >=1.10.0
    - nlohmann_json >=3.7.0
  run:
    - python

test:
  commands:
    - conda list
    - test -d ${PREFIX}/include/ChemicalFun  # [unix]
    - test -f ${PREFIX}/include/ChemicalFun/FormulaParser.h  # [unix]
    - if exist %LIBRARY_PREFIX%\include\ChemicalFun\FormulaParser.h (exit 0) else (exit 1)  # [win]
  imports:
    - chemicalfun

about:
  home: https://github.com/thermohub/chemicalfun
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: Library for generating balanced chemical reactions and for parsing and calculating properties of chemical formulas.
  doc_url: https://github.com/thermohub/chemicalfun
  dev_url: https://github.com/thermohub/chemicalfun

extra:
  recipe-maintainers:
    - gdmiron
    - dimitrikulik
    - sdmytrievs
    - allanleal
